# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc2aca82efff285719be566633e39531f05c29f9c9d09780fdc13bf834990e9bb52956c37704067b6d0523fd35cf6d94d8391c70b9167c40f1ab1a6dbd31ad69

test:
  secret_key_base: 680d5f4a96eea4bdd90d8d1686f9c6052a96e8b74c649654b5e1c9833572f97fd591e248fef66a1348eeaab9765c0015d751764e17cd8417bc8c973c786e7c41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
